# Generated by Django 4.1.10 on 2023-07-13 23:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hello_world", "0003_defaultchatsettings_description_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chatsession",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
